covariates:
  - hs_fam_car
  - hs_c_room
  - hs_travel_hol
  - hs_comp_hm
  - hs_marital_m
  - hs_wrk_m
  - hs_finance
  - FAS_score
  - FAS_cat
  - hs_help_neigh
  - hs_trust_neigh
  - hs_ask_advice
  - hs_contact_fam
  - contactfam_3cat
  - contactfam_3cat_num
  - hs_tob
  - hs_cig_w
  - hs_cig_whm
  - hs_smk_partner
  - hs_cig_partner_w
  - hs_cig_partner_whm
  - hs_smk_oth1
  - hs_cig_oth1_whm
  - hs_cig_oth2
  - hs_cig_oth2_whm
  - hs_cin_smk
  - hs_cin_smk_w
  - hs_smk_parents
  - hs_globalexp
  - hs_globalexp2
  - h_sex
  - h_date_birth
  - hs_age_years
  - HelixID
  - cohort
  - hs_Ethnic
  - h_ethnicity_c
  - hs_Gender
  - hs_Smoker
  - hs_Age
  - hs_numsiblings
clinical:
  - asthma
  - hs_c_height
  - hs_c_weight
  - hs_c_bmi
  - hs_bp_sys
  - hs_bp_dia
  - hs_waist
  - hs_midup_arm
  - hs_head_circ
  - hs_w2h
  - hs_tricep
  - hs_subs_capular
  - hs_suprailiac
  - hs_thigh
  - hs_skf_sum4
  - hs_skf_sum2
  - hs_fatprop
  - hs_fatmass
  - hs_freefatmass_bia
  - hs_fatmass_bia
  - hs_fatprop_bia
  - hs_hdlchol_mgdl
  - hs_Esc_AD
  - hs_Esc_RD
  - hs_Esc_Som
  - hs_Esc_Soc
  - hs_Esc_Pen
  - hs_Esc_Ate
  - hs_Esc_Nor
  - hs_Esc_Agr
  - hs_Esc_Otr
  - hs_DSM_Afe
  - hs_DSM_Ans
  - hs_DSM_Som
  - hs_DSM_TDAH
  - hs_DSM_Opo
  - hs_DSM_Con
  - hs_Gen_Int
  - hs_Gen_Ext
  - hs_Gen_Tot
  - hs_Oposic_raw
  - hs_Cognit_raw
  - hs_Hyper_raw
  - hs_ADHD_raw
  - hs_ADHD_raw_Cat
  - GPF
  - INT
  - EXT
  - hs_asthma
  - hs_Asthma_spiro
  - hs_Height
  - hs_Weight
  - hs_Asthma_HelixQuest
